version: '3.9'

services:
  app:
    container_name: "wagon-depot"
    build: ./
    ports:
      - "80:80"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    container_name: depotDB
    ports:
      - "54321:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root